# 1.	Which apps have the highest rating in the given available dataset?
SELECT App, Rating 
FROM playstore.playstore_apps_cleaned
WHERE Rating IN (SELECT MAX(Rating) FROM playstore.playstore_apps_cleaned)
ORDER BY Rating DESC, Reviews DESC;

# 2.	What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
SELECT App, Rating, Reviews, Installs
FROM playstore.playstore_apps_cleaned
WHERE Rating IN (SELECT MAX(Rating) FROM playstore.playstore_apps_cleaned)
ORDER BY Reviews DESC;

#3.	Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
SELECT App, Reviews, Category
FROM playstore.playstore_apps_cleaned
WHERE Reviews IN (SELECT MAX(Reviews) FROM playstore.playstore_apps_cleaned);

# 4.	What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
SELECT SUM(Installs * Price) AS Total_Revenue
FROM playstore.playstore_apps_cleaned
WHERE Type = 'Paid';

# 5.	Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
SELECT Category, SUM(Installs) AS Total_Installs
FROM playstore_apps_cleaned
GROUP BY Category
ORDER BY Total_Installs DESC
LIMIT 1;

# 6.	Which Genre has the most number of published apps?
SELECT Genres, COUNT(*) AS Num_of_Apps
FROM playstore_apps_cleaned
GROUP BY Genres
ORDER BY Num_of_Apps DESC
LIMIT 1;

 # 7.	Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top (to avoid duplicate results use distinct)
SELECT DISTINCT App, Installs
FROM playstore_apps_cleaned
WHERE Category = 'GAME'
ORDER BY Installs DESC;

# 8.	Provide the list of apps that can work on android version 4.0.3 and up.
SELECT App
FROM playstore_apps_cleaned
WHERE Android_Ver = '4.0.3 and up';

# 9.	How many apps from the given data set are free? Also, provide the number of paid apps.
SELECT
    SUM(CASE WHEN Type = 'Free' THEN 1 ELSE 0 END) AS Num_Free_Apps,
    SUM(CASE WHEN Type = 'Paid' THEN 1 ELSE 0 END) AS Num_Paid_Apps
FROM playstore_apps_cleaned;


# 10.	Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
SELECT App
FROM playstore_apps_cleaned
WHERE Category = 'DATING'
ORDER BY Reviews DESC
LIMIT 1;

# 11.	Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.
SELECT App, Sentiment, COUNT(Sentiment) AS Num_Reviews
FROM playstore_reviews_cleaned
WHERE App = '10 Best Foods for You'
GROUP BY Sentiment
HAVING Sentiment IN ('Positive', 'Negative');

# 12.	Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT Translated_Review
FROM playstore_reviews_cleaned
WHERE App = 'ASUS SuperNote' and Sentiment_Polarity = 1 and Sentiment_Subjectivity = 1;

# 13.	Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
SELECT Translated_Review
FROM playstore_reviews_cleaned
WHERE App = 'Abs Training-Burn belly fat' and Sentiment = 'Neutral';

# 14.	Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
SELECT Translated_Review, Sentiment_Polarity, Sentiment_Subjectivity 
FROM playstore_reviews_cleaned
WHERE App = 'Adobe Acrobat Reader' and Sentiment = 'Negative';
